### ISSUE TITLE
Chose a storage option

### ISSUE THREAD

**Issue by TendTo** [UNICT-DMI/ERSU-Bot#17]
How should the data be stored locally? Shall we continue using **sqlite**? Do you want to try some other approach (**json**, **mysql**)?
Once the choice is made, it should be consistent.

**Comment by Helias** [comment]
@TendTo I would like to use sqlite because it's quite simple and this project.
If for **json you mean NoSQL, that's an option but json files do not fit for this project, we need a dynamic db for the menu-notification system.

Moreover, I am not sure if this project rewrites from new devs is a good occasion to experiment new systems beside the standard used like sqlite.

What are the PROs and CONs of other data storage considering the feature menu-notification? (It will change the data in the database weekly)

**Comment by Helias** [comment]
can we close this?

**Comment by InfraBlue0** [comment]
I think so, we have chosen sqlite3 for saving all settings data from users.
